CALL APP_OPERATIONS.GRANT_DATABASE_ROLES_TO_WRAPPERS('XXXX', 'test');
----
CREATE OR REPLACE PROCEDURE APP_OPERATIONS.SUMMIT_XXXX_INSTALLER()
  RETURNS STRING
  LANGUAGE SQL
AS
$$
BEGIN
    GRANT DATABASE ROLE SUMMIT_SHARED_DB_ROLE TO DATABASE ROLE APP_EXPORTER;

CREATE SCHEMA YY_VENDORDATA_XXXX;

GRANT USAGE ON SCHEMA YY_VENDORDATA_XXXX TO DATABASE ROLE APP_EXPORTER;

    GRANT CREATE TABLE ON SCHEMA YY_VENDORDATA_XXXX TO DATABASE ROLE APP_EXPORTER;

CREATE DATABASE ROLE CONSUMER_APP_DB_ROLE;

    GRANT DATABASE ROLE CONSUMER_APP_DB_ROLE TO DATABASE ROLE APP_EXPORTER;

CALL APP_OPERATIONS.INSTALL_BUSINESS_OBJECTS('YY_VENDORDATA_XXXX', 'CONSUMER_APP_DB_ROLE');
END;
$$;
----
DROP SHARE IF EXISTS SUMMIT_XXXX_SHARE;
----
CREATE SHARE SUMMIT_XXXX_SHARE installer = APP_OPERATIONS.SUMMIT_XXXX_INSTALLER();
----
GRANT USAGE ON DATABASE "SUMMIT_NATIVE_APP_DB" TO SHARE SUMMIT_XXXX_SHARE;
----
GRANT USAGE ON DATABASE "SUMMIT_NATIVE_APP_DB" TO DATABASE ROLE SUMMIT_SHARED_DB_ROLE;
----
GRANT USAGE ON DATABASE "SUMMIT_NATIVE_APP_DB" TO DATABASE ROLE SUMMIT_LOCAL_DB_ROLE;
----
GRANT USAGE ON SCHEMA "SUMMIT_NATIVE_APP_DB"."APP_OPERATIONS" to DATABASE ROLE SUMMIT_SHARED_DB_ROLE;
----
GRANT USAGE ON SCHEMA "SUMMIT_NATIVE_APP_DB"."APP_OPERATIONS" to DATABASE ROLE SUMMIT_LOCAL_DB_ROLE;
----
GRANT REFERENCE_USAGE ON DATABASE SUMMIT_MDM_DATA TO SHARE SUMMIT_XXXX_SHARE;
----
grant select on view "SUMMIT_NATIVE_APP_DB"."APP_OPERATIONS".VENTITLEMENTS to database role SUMMIT_LOCAL_DB_ROLE;
----
grant usage on procedure "SUMMIT_NATIVE_APP_DB".APP_OPERATIONS.INSTALL_BUSINESS_OBJECTS(VARCHAR, VARCHAR) to database role SUMMIT_SHARED_DB_ROLE;
----
grant usage on procedure "SUMMIT_NATIVE_APP_DB".APP_OPERATIONS.INSTALL_BUSINESS_OBJECTS(VARCHAR, VARCHAR) to database role SUMMIT_LOCAL_DB_ROLE;
----
grant usage on procedure "SUMMIT_NATIVE_APP_DB".APP_OPERATIONS.SUMMIT_XXXX_INSTALLER() to database role SUMMIT_SHARED_DB_ROLE;
----
grant usage on procedure "SUMMIT_NATIVE_APP_DB".APP_OPERATIONS.SUMMIT_XXXX_INSTALLER() to database role SUMMIT_LOCAL_DB_ROLE;
----
GRANT USAGE ON SCHEMA "SUMMIT_NATIVE_APP_DB"."APP_FUNC_XXXX_SHARE" TO DATABASE ROLE SUMMIT_LOCAL_DB_ROLE;
----
GRANT DATABASE ROLE "SUMMIT_NATIVE_APP_DB".SUMMIT_SHARED_DB_ROLE TO SHARE SUMMIT_XXXX_SHARE;
----
GRANT DATABASE ROLE "SUMMIT_NATIVE_APP_DB".SUMMIT_LOCAL_DB_ROLE TO SHARE SUMMIT_XXXX_SHARE;
